layers: [15,25,25,1]
learning_rate: 0.0002
batch_size: 32
epochs: 5
no_epochs_dataset: 10
perc_eval: 0.1
multiple_data: False
data_file: "../data/processed/zone/train/train_zone_permuted_shuffled.csv"
data_length: 270000000
save_network_to: "F-zoneNN"
weight_initializer: xavier
transfer_function: relu
activation_function: sigmoid
cost_function: sigmoid cross-entropy
optimizer: adam
dropout: 0.0
offset: 4
seed_init: 1 # use fix seeds to reproduce the network exactly else remove seeds
seed_shuffle: 1
log_level: info # can be debug, error, fatal, info or warn
