layers: 
  - type: dense
    units: 128
    activation: relu
  - type: dense
    units: 64
    activation: relu
  - type: dense
    units: 32
    activation: relu
  - type: dense
    units: 1
    activation: sigmoid

learning_rate: 0.0001                # Lernrate für den Optimizer
batch_size: 32                       # Größe der Batches
epochs: 20                           # Anzahl der epochs (gesamt 20, eine dauert ca 10h auf dem Server)
no_epochs_dataset: 10                # Anzahl der Wiederholungen des gesamten Datensatzes pro Epoche
perc_eval: 0.1                       # Anteil der Daten, die zur Validierung verwendet werden (10%)
#multiple_data: False # Was ist das? !Unterschied!
data_file: "../data/processed/zone/train/train_zone_permuted_shuffled.csv"  # Pfad zur Datei mit den Trainingsdaten
data_length: 270000000               # Gesamtanzahl der Datenzeilen in der CSV-Datei
save_network_to: "kan_model"         # Pfad für das Speichern des trainierten Modells
weight_initializer: xavier           # Initialisierer für die Gewichtung
transfer_function: relu              # Transferfunktion für versteckte Schichten
activation_function: sigmoid         # Aktivierungsfunktion für die Ausgabeschicht
cost_function: binary_crossentropy   # Kostenfunktion (angepasst zu binary_crossentropy)
optimizer: adam                      # Optimizer (Adam wird verwendet)
dropout: 0.0                         # Dropout-Rate zur Vermeidung von Overfitting
offset: 4                            # Offset für die Eingabedaten
seed_init: 1                         # Seed zur Initialisierung (zur Reproduzierbarkeit)
seed_shuffle: 1                      # Seed zum Shuffeln der Daten
#shuf_buffer: 1000                    # Buffergröße beim Shuffeln (Standardwert 1000)
#beta1: 0.9                           # Beta1 für den Adam-Optimizer
#beta2: 0.999                         # Beta2 für den Adam-Optimizer
#use_bias: True                       # Bias in den Schichten verwenden
log_level: info                      # Log-Level (kann debug, error, fatal, info oder warn sein)
